### ISSUE TITLE
diamond不开源了吗？

### ISSUE THREAD

**Issue by CodeToSurvive1** [takeseem/diamond#3]
http://code.taobao.org/p/diamond/src/这个链接好像失效了 其他的地方也没找到

**Comment by CodeToSurvive1** [comment]
好像现在不叫diamond了 改成edas-config-center了

**Comment by takeseem** [comment]
@CodeToSurvive1 非常抱歉这么长时间才回复（家里小孩生病了）。
当时2014年研究tddl时，被告之希望我删除github上的相关fork，diamond是淘宝的一个配置服务组件，阿里确实当年开源了大约一年就关闭了很多开源项目（**当然很多链接也失效了**）。diamond其实并不复杂，而且开源出来的和tddl也不配套，要旧，如果要配套需要自己根据tddl的使用，改写下并不复杂。

edas-config-center：是一个配置服务，不过是阿里云战略的一部分，两者定位不同。
